#!/usr/bin/env bash
# Update the package list to get the latest information about available packages

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Create a simple HTML page with the content "Hello World!"
echo 'Hello World!' >  /var/www/html/index.html

# Restart Nginx
sudo service nginx start
echo "Nginx installation and configuration completed."
