#!/usr/bin/env bash

# Configure web-02 to be identical to web-01
sudo apt-get update
sudo apt-get install nginx -y

# Create a page displaying "hello world"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat <<EOF >> /etc/nginx/sites-available/default
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                internal;
        }
EOF'

# Create a variable to store the hostname of the server
HOSTNAME=$(hostname)

# Add custom header configuration to Nginx
sudo bash -c 'cat <<EOF >> /etc/nginx/nginx.conf
http {
    add_header X-Served-By $HOSTNAME;
    # Other existing configurations...
}
EOF'

# Restart the web server after updating the settings
sudo service nginx restart

